tunnel: tracker-api
credentials-file: C:\Users\ACER\.cloudflared\4b4faa81-227a-49ba-ba55-610f1a12624d.json
protocol: http2

ingress:
  # Backend (FastAPI)
  - hostname: api.gadget4me.in
    service: http://127.0.0.1:8001
    originRequest:
      httpHostHeader: 127.0.0.1:8001

  # Frontend (React / Vite)
  - hostname: app.gadget4me.in
    service: http://127.0.0.1:8080
    originRequest:
      httpHostHeader: 127.0.0.1:8080

  - service: http_status:404
